#!/bin/bash

# --- 1. SET YOUR SHARED VARIABLES ---
Thread=16
genomdir=./GRCm39_Reference
genome=${genomdir}/mm39.AG_conversion.fa
genome2=${genomdir}/mm39.fa
rvsgenome=${genomdir}/mm39.rvsCom.fa
TfGenome=${genomdir}/GCF_000001635.27_GRCm39_rna2.fa.AG_conversion.fa

annodir=./GRCm39_Reference
baseanno=${annodir}/GCF_000001635.27_GRCm39_genomic.gtf_change2Ens.tbl2.noredundance.base
anno=${annodir}/GCF_000001635.27_GRCm39_genomic.gtf_change2Ens.tbl2

outputdir=./GLORI_results
tooldir=./GLORI-tools-1.0.0

# Create output directory if it doesn't exist
mkdir -p $outputdir

# --- 2. LOOP THROUGH YOUR CLEANED FILES ---
# This points to the files generated by your preprocessing script
for file in ./FASTQ_file/cleaned_reads/SRR31477251_test_clean.fq; do
    
    # Extract the base name (e.g., SRR31477251_clean) to use as a unique prefix
    base=$(basename $file .fq)
    prx=${base}_mapped
    
    echo "========================================"
    echo "Running GLORI pipeline for $base..."
    echo "========================================"
    
    python ${tooldir}/run_GLORI.py \
        -i $tooldir \
        -q ${file} \
        -T $Thread \
        -f ${genome} \
        -f2 ${genome2} \
        -rvs ${rvsgenome} \
        -Tf ${TfGenome} \
        -a $anno \
        -b $baseanno \
        -pre ${prx} \
        -o $outputdir \
        --combine \
        --rvs_fac
        
    echo "Finished mapping $base!"
done